package com.gi.xm.es.util;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by vincent on 17-4-28.
 */
public  class  ESEXEC {

    public static Map<String,String>  ADDINDEX = new HashMap<>();

    static {
          //ADDINDEX.put("xm_project","curl -XPUT 10.9.130.135:9200/xm_project -d '{\"mappings\" : {\"project\": {\"properties\": {\"indudstrySubName\": {\"analyzer\": \"ik_smart\",\"type\": \"text\"},\"indudstryName\": {\"analyzer\": \"ik_smart\",\"type\": \"text\"},\"icon\": {\"type\": \"text\"},\"description\": {\"analyzer\": \"ik_max_word\",\"type\": \"text\"},\"logo\": {\"type\": \"text\"},\"roundName\": {\"analyzer\": \"ik_smart\",\"type\": \"text\"},\"title\": {\"analyzer\": \"ik_max_word\",\"type\": \"text\"},\"lables\": {\"analyzer\": \"ik_max_word\",\"type\": \"text\"},\"createDate\": {\"type\": \"text\"},\"sid\": {\"type\": \"text\"}}}}}'");
          ADDINDEX.put("ctdn_project","curl -XPUT 10.9.130.135:9200/ctdn_project -d '{ \"mappings\" : { \"project\": { \"properties\": { \"id\":{ \"type\": \"long\" }, \"code\":{ \"type\": \"keyword\" }, \"industryName\":{ \"type\": \"keyword\" }, \"industrySubName\":{ \"type\": \"keyword\" }, \"industryGrandSonName\":{ \"type\": \"keyword\" }, \"industryIds\":{ \"type\": \"keyword\" }, \"latestFinanceRound\":{ \"type\":\"keyword\" }, \"districtId\":{ \"type\": \"long\" }, \"districtSubId\":{ \"type\": \"long\" }, \"addr\":{ \"type\": \"keyword\" }, \"logo\":{ \"type\": \"keyword\" }, \"projTitle\":{ \"type\": \"keyword\" }, \"setupDT\": { \"type\": \"date\" }, \"latestFinanceDT\":{ \"type\": \"date\" }, \"latestFinanceAmountStr\":{ \"type\": \"keyword\" }, \"latestFinanceAmountNum\":{ \"type\": \"integer\" }, \"loadDate\":{ \"type\":\"date\" } } } } }'");
          ADDINDEX.put("ctdn_investfirms","curl -XPUT 10.9.130.135:9200/ctdn_investfirms -d '{ \"mappings\" : { \"investfirms\": { \"properties\": { \"id\":{ \"type\": \"long\" }, \"code\":{ \"type\": \"long\" }, \"focusDomain\":{ \"type\": \"keyword\" }, \"industryIds\":{ \"type\": \"keyword\" }, \"investStage\":{ \"type\": \"keyword\" }, \"orgType\":{ \"type\": \"keyword\" }, \"districtId\":{ \"type\": \"long\" }, \"districtSubId\":{ \"type\": \"long\" }, \"capitalType\":{ \"type\":\"keyword\" }, \"currencyTitle\":{ \"type\": \"keyword\" }, \"logo\":{ \"type\": \"keyword\" }, \"orgName\":{ \"type\": \"keyword\" }, \"investTotal\":{ \"type\": \"integer\" }, \"totalRatio\":{ \"type\": \"integer\" }, \"investAmountNum\":{ \"type\": \"long\" }, \"investAmountStr\":{ \"type\": \"keyword\" }, \"amountRatio\":{ \"type\": \"integer\" }, \"investProj\":{ \"type\": \"keyword\" }, \"newestInvestDate\":{ \"type\": \"date\" } } } } }'");
          ADDINDEX.put("ctdn_invest_event","curl -XPUT 10.9.130.135:9200/ctdn_invest_event -d '{ \"mappings\" : { \"invest_event\": { \"properties\": { \"id\":{ \"type\": \"long\" }, \"code\":{ \"type\": \"keyword\" }, \"sourceId\":{ \"type\": \"long\" }, \"sourceCode\":{ \"type\": \"keyword\" }, \"industryIds\":{ \"type\": \"keyword\" }, \"industryName\":{ \"type\": \"keyword\" }, \"industrySubName\":{ \"type\": \"keyword\" }, \"round\":{ \"type\":\"keyword\" }, \"districtId\":{ \"type\": \"long\" }, \"districtSubId\":{ \"type\": \"long\" }, \"district\":{ \"type\": \"keyword\" }, \"logo\":{ \"type\": \"keyword\" }, \"company\":{ \"type\": \"keyword\" }, \"investdate\": { \"type\": \"date\" }, \"amountStr\":{ \"type\":\"keyword\" }, \"amountNum\":{ \"type\":\"integer\" }, \"currencyTitle\":{ \"type\":\"keyword\" }, \"investSideJson\":{ \"type\":\"keyword\" }, \"bodyRole\":{ \"type\":\"keyword\" }, \"sourceType\":{ \"type\":\"keyword\" }, \"isClick\":{ \"type\":\"keyword\" } } } } }'");
          ADDINDEX.put("ctdn_launch_event","curl -XPUT 10.9.130.135:9200/ctdn_launch_event -d '{ \"mappings\" : { \"launch_event\": { \"properties\": { \"id\":{ \"type\": \"long\" }, \"code\":{ \"type\": \"keyword\" }, \"sourceId\":{ \"type\": \"long\" }, \"sourceCode\":{ \"type\": \"keyword\" }, \"industryIds\":{ \"type\": \"keyword\" }, \"industryName\":{ \"type\": \"keyword\" }, \"industrySubName\":{ \"type\": \"keyword\" }, \"type\":{ \"type\": \"keyword\" }, \"stockExchange\":{ \"type\": \"keyword\" }, \"transferType\":{ \"type\": \"keyword\" }, \"marketLayer\":{ \"type\": \"keyword\" }, \"listedDate\":{ \"type\": \"date\" }, \"district\":{ \"type\": \"keyword\" }, \"logo\":{ \"type\": \"keyword\" }, \"company\":{ \"type\": \"keyword\" }, \"stockCode\": { \"type\": \"keyword\" }, \"bodyRole\":{ \"type\":\"keyword\" }, \"sourceType\":{ \"type\":\"keyword\" }, \"isClick\":{ \"type\":\"keyword\" } } } } }'");
          ADDINDEX.put("ctdn_merge_event","curl -XPUT 10.9.130.135:9200/ctdn_merge_event -d '{ \"mappings\" : { \"merge_event\": { \"properties\": { \"id\":{ \"type\": \"long\" }, \"code\":{ \"type\": \"keyword\" }, \"sourceId\":{ \"type\": \"long\" }, \"sourceCode\":{ \"type\": \"keyword\" }, \"industryIds\":{ \"type\": \"keyword\" }, \"industryName\":{ \"type\": \"keyword\" }, \"industrySubName\":{ \"type\": \"keyword\" }, \"district\":{ \"type\": \"keyword\" }, \"mergeType\":{ \"type\": \"keyword\" }, \"mergeState\":{ \"type\": \"keyword\" }, \"currencyTitle\":{ \"type\": \"keyword\" }, \"equityRate\":{ \"type\":\"integer\" }, \"mergeBeginDate\":{ \"type\":\"date\" }, \"mergeEndDate\":{ \"type\":\"date\" }, \"mergeOrderDate\":{ \"type\":\"date\" }, \"logo\":{ \"type\": \"keyword\" }, \"projTitle\":{ \"type\": \"keyword\" }, \"amountStr\":{ \"type\":\"keyword\" }, \"amountNum\":{ \"type\": \"integer\" }, \"mergeSideJson\":{ \"type\":\"keyword\" }, \"bodyRole\":{ \"type\":\"keyword\" }, \"sourceType\":{ \"type\":\"keyword\" }, \"isClick\":{ \"type\":\"keyword\" } } } } }'");
          ADDINDEX.put("ctdn_quit_event","curl -XPUT 10.9.130.135:9200/ctdn_quit_event -d '{ \"mappings\" : { \"quit_event\": { \"properties\": { \"id\":{ \"type\": \"long\" }, \"code\":{ \"type\": \"keyword\" }, \"sourceId\":{ \"type\": \"long\" }, \"sourceCode\":{ \"type\": \"keyword\" }, \"industryIds\":{ \"type\": \"keyword\" }, \"industryName\":{ \"type\": \"keyword\" }, \"industrySubName\":{ \"type\": \"keyword\" }, \"quitType\":{ \"type\": \"keyword\" }, \"districtId\":{ \"type\": \"long\" }, \"districtSubId\":{ \"type\": \"long\" }, \"district\":{ \"type\": \"keyword\" }, \"logo\":{ \"type\": \"keyword\" }, \"company\":{ \"type\": \"keyword\" }, \"quitDate\":{ \"type\": \"date\" }, \"quitAmountStr\":{ \"type\":\"keyword\" }, \"quitAmountNum\":{ \"type\":\"integer\" }, \"currencyTitle\":{ \"type\":\"keyword\" }, \"quitSideJson\":{ \"type\":\"keyword\" }, \"bodyRole\":{ \"type\":\"keyword\" }, \"sourceType\":{ \"type\":\"keyword\" }, \"isClick\":{ \"type\":\"keyword\" } } } } }'");
    }
}
